using AiVideoEditor.Core.Common;
using AiVideoEditor.Core.Entities;
using AiVideoEditor.Core.Interfaces;
using AiVideoEditor.Infrastructure;
using AiVideoEditor.Infrastructure.Configuration;
using AiVideoEditor.Timeline;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Extensions.Options;
using Xunit;

namespace AiVideoEditor.Video.Tests;

/// <summary>
/// D026 §3 (Step 11.4) with the real ffprobe: the relink check of files generated by ffmpeg — a shorter file is
/// rejected, another resolution is a warning, an mp4 with sound only is not a video, the same kind of file passes and
/// is applied with its probed metadata. The old file never existed (the asset is offline). The project service is a
/// small stand-in (this test project doesn't reference Project): it re-checks with <c>File.Exists</c> and tells
/// nothing.
/// </summary>
public sealed class MediaRelinkIntegrationTests : IDisposable
{
    private static readonly FrameRate Rate = FrameRate.Fps25;
    private readonly string _dir = Path.Combine(Path.GetTempPath(), "aive-relink-integration", Guid.NewGuid().ToString("N"));

    public MediaRelinkIntegrationTests() => Directory.CreateDirectory(_dir);

    public void Dispose()
    {
        try { Directory.Delete(_dir, recursive: true); } catch (IOException) { }
    }

    private string Video(string name, double seconds, string size = "640x360", bool sound = true)
    {
        var path = Path.Combine(_dir, name);
        var args = new List<string> { "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i", $"testsrc2=s={size}:r=25:d={seconds}" };
        if (sound) args.AddRange(new[] { "-f", "lavfi", "-i", $"sine=f=440:r=48000:d={seconds}", "-c:a", "aac", "-shortest" });
        args.AddRange(new[] { "-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p", path });
        TestMedia.Run(FfmpegTools.Ffmpeg!, args);
        return path;
    }

    private string SoundOnlyMp4(string name, double seconds)
    {
        var path = Path.Combine(_dir, name);
        TestMedia.Run(FfmpegTools.Ffmpeg!, new[] { "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi", "-i",
            $"sine=f=440:r=48000:d={seconds}", "-c:a", "aac", path });
        return path;
    }

    private static FfprobeMediaAnalysisService Probe() => FfmpegTools.Analysis();

    /// <summary>What the relink needs from the project service: the project, the re-check and the notifications.</summary>
    private sealed class OneProject : IProjectService
    {
        public Core.Entities.Project Current { get; } = new();
        public event EventHandler? ProjectChanged { add { } remove { } }
        public event EventHandler? MediaAssetsChanged { add { } remove { } }
        public event EventHandler? TimelineChanged { add { } remove { } }
        public event EventHandler? SaveStateChanged { add { } remove { } }
        public event EventHandler? ProjectSaved { add { } remove { } }
        public event EventHandler<MediaAvailabilityChangedEventArgs>? MediaAvailabilityChanged { add { } remove { } }
        public event EventHandler<MediaRelinkedEventArgs>? MediaRelinked { add { } remove { } }
        public Core.Entities.Project CreateNew(string name, ProjectSettings? settings = null) => throw new NotSupportedException();
        public Task<Core.Entities.Project> OpenAsync(string projectFolderPath, CancellationToken ct = default) => throw new NotSupportedException();
        public Task<Core.Entities.Project> RestoreRecoveryAsync(string recoveryFilePath, CancellationToken ct = default) => throw new NotSupportedException();
        public Task SaveAsync(CancellationToken ct = default) => throw new NotSupportedException();
        public Task SaveAsAsync(string projectFolderPath, CancellationToken ct = default) => throw new NotSupportedException();
        public Task RecheckMediaAsync(CancellationToken ct = default)
        {
            foreach (var asset in Current.MediaAssets) asset.IsMissing = !File.Exists(asset.FilePath);
            return Task.CompletedTask;
        }
        public void NotifyMediaRelinked(IReadOnlyList<MediaFileReplacement> replacements) { }
        public MediaAddResult AddMediaAssets(IEnumerable<MediaAsset> assets) => throw new NotSupportedException();
        public void NotifyMediaAssetsChanged() { }
        public void NotifyTimelineChanged() { }
    }

    private sealed record Setup(OneProject Projects, UndoRedoService Undo, MediaRelinkService Relink, MediaAsset Asset);

    /// <summary>A project with one offline video (metadata of a 4 s 640×360 file) whose clip uses its first 3 s.</summary>
    private async Task<Setup> OfflineVideoWithClip()
    {
        var undo = new UndoRedoService();
        var projects = new OneProject();
        projects.Current.Settings.FrameRate = Rate;
        var probe = Probe();
        var original = (await probe.AnalyzeAsync(Video("original.mp4", 4))).Metadata!;
        var asset = new MediaAsset
        {
            FilePath = Path.Combine(_dir, "gone", "original.mp4"), Kind = MediaKind.Video,
            AnalysisStatus = MediaAnalysisStatus.Completed, Metadata = original
        };
        projects.Current.MediaAssets.Add(asset);
        var v1 = new Track { Type = TrackType.Video, Name = "V1" };
        projects.Current.Timeline.VideoTracks.Add(v1);
        v1.Clips.Add(new VideoClip
        {
            MediaAssetId = asset.Id, TimelineStart = MediaTime.Zero, Duration = MediaTime.FromFrame(75, Rate),
            SourceIn = MediaTime.Zero, SourceOut = MediaTime.FromFrame(75, Rate)
        });
        return new Setup(projects, undo, new MediaRelinkService(projects, undo, probe, NullLogger<MediaRelinkService>.Instance), asset);
    }

    [FfmpegFact]
    public async Task A_shorter_file_is_rejected()
    {
        var s = await OfflineVideoWithClip();
        var check = await s.Relink.CheckAsync(s.Asset.Id, Video("short.mp4", 2));
        Assert.Equal(RelinkRejection.TooShort, check.Rejection);
    }

    [FfmpegFact]
    public async Task A_sound_only_mp4_is_not_a_video()
    {
        var s = await OfflineVideoWithClip();
        var check = await s.Relink.CheckAsync(s.Asset.Id, SoundOnlyMp4("sound.mp4", 4));
        Assert.Equal(RelinkRejection.WrongMediaType, check.Rejection);
    }

    [FfmpegFact]
    public async Task Another_resolution_is_a_warning_and_the_same_kind_of_file_is_applied_with_its_probed_metadata()
    {
        var s = await OfflineVideoWithClip();
        var larger = await s.Relink.CheckAsync(s.Asset.Id, Video("hd.mp4", 4, "1280x720"));
        Assert.True(larger.CanApply, larger.Message);
        Assert.Equal(RelinkWarningKind.DisplaySize, Assert.Single(larger.Warnings).Kind);

        var same = await s.Relink.CheckAsync(s.Asset.Id, Video("same.mp4", 5));
        Assert.True(same.CanApply, same.Message);
        Assert.Empty(same.Warnings);
        var result = await s.Relink.ApplyAsync(same);

        Assert.True(result.Applied, result.Message);
        Assert.Equal(Path.Combine(_dir, "same.mp4"), s.Asset.FilePath);
        Assert.False(s.Asset.IsMissing);
        Assert.Equal(MediaAnalysisStatus.Completed, s.Asset.AnalysisStatus);
        Assert.True(s.Asset.Metadata!.Duration >= MediaTime.FromSeconds(4.9));
        Assert.Equal("h264", s.Asset.Metadata.VideoCodec);
        Assert.Equal(new FileInfo(s.Asset.FilePath).Length, s.Asset.FileSizeBytes);
        Assert.True(s.Undo.CanUndo);
    }
}
